# Generated by Django 5.1.4 on 2024-12-31 02:57

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="PromptModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("field", models.CharField(max_length=255)),
                ("topics", models.CharField(max_length=255)),
                ("file", models.FileField(upload_to="")),
            ],
        ),
    ]
